# coding=utf-8
from .SWFEvent import SWFEvent

class CancelTimerFailedEvent(SWFEvent):
    '''
    Failed to process CancelTimer decision. This happens when the decision isn't configured properly, for example no timer exists with the specified timer Id.

    'cancelTimerFailedEventAttributes': {
        'timerId': 'string',
        'cause': 'TIMER_ID_UNKNOWN'|'OPERATION_NOT_PERMITTED',
        'decisionTaskCompletedEventId': 123
    },
    '''

    

    @property
    def timer_id(self):
        '''
        The timerId provided in the CancelTimer decision that failed.
    
        :return string:
        '''
        return self._get_string_data_attr('timerId')
    
    
    @property
    def cause(self):
        '''
        The cause of the failure. This information is generated by the system and can be useful for diagnostic purposes.
    
        Note
        If cause is set to OPERATION_NOT_PERMITTED , the decision failed because it lacked sufficient permissions. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer Guide .
    
        :return string:
        '''
        return self._get_string_data_attr('cause')
    
    
    @property
    def decision_task_completed_event_id(self):
        '''
        The ID of the DecisionTaskCompleted event corresponding to the decision task that resulted in the CancelTimer decision to cancel this timer. This information can be useful for diagnosing problems by tracing back the chain of events leading up to this event.
    
        :return integer:
        '''
        return self._get_integer_data_attr('decisionTaskCompletedEventId')
    
    
