# coding=utf-8
from .SWFEvent import SWFEvent

class RequestCancelActivityTaskFailedEvent(SWFEvent):
    '''
    Failed to process RequestCancelActivityTask decision. This happens when the decision isn't configured properly.

    'requestCancelActivityTaskFailedEventAttributes': {
        'activityId': 'string',
        'cause': 'ACTIVITY_ID_UNKNOWN'|'OPERATION_NOT_PERMITTED',
        'decisionTaskCompletedEventId': 123
    },
    '''

    

    @property
    def activity_id(self):
        '''
        The activityId provided in the RequestCancelActivityTask decision that failed.
    
        :return string:
        '''
        return self._get_string_data_attr('activityId')
    
    
    @property
    def cause(self):
        '''
        The cause of the failure. This information is generated by the system and can be useful for diagnostic purposes.
    
        Note
        If cause is set to OPERATION_NOT_PERMITTED , the decision failed because it lacked sufficient permissions. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer Guide .
    
        :return string:
        '''
        return self._get_string_data_attr('cause')
    
    
    @property
    def decision_task_completed_event_id(self):
        '''
        The ID of the DecisionTaskCompleted event corresponding to the decision task that resulted in the RequestCancelActivityTask decision for this cancellation request. This information can be useful for diagnosing problems by tracing back the chain of events leading up to this event.
    
        :return integer:
        '''
        return self._get_integer_data_attr('decisionTaskCompletedEventId')
    
    
