from .SWFEvent import SWFEvent

class ScheduleActivityTaskFailedEvent(SWFEvent):
    '''
    Failed to process ScheduleActivityTask decision. This happens when the decision isn't configured properly, for example the activity type specified isn't registered.

    'scheduleActivityTaskFailedEventAttributes': {
        'activityType': {
            'name': 'string',
            'version': 'string'
        },
        'activityId': 'string',
        'cause': 'ACTIVITY_TYPE_DEPRECATED'|'ACTIVITY_TYPE_DOES_NOT_EXIST'|'ACTIVITY_ID_ALREADY_IN_USE'|'OPEN_ACTIVITIES_LIMIT_EXCEEDED'|'ACTIVITY_CREATION_RATE_EXCEEDED'|'DEFAULT_SCHEDULE_TO_CLOSE_TIMEOUT_UNDEFINED'|'DEFAULT_TASK_LIST_UNDEFINED'|'DEFAULT_SCHEDULE_TO_START_TIMEOUT_UNDEFINED'|'DEFAULT_START_TO_CLOSE_TIMEOUT_UNDEFINED'|'DEFAULT_HEARTBEAT_TIMEOUT_UNDEFINED'|'OPERATION_NOT_PERMITTED',
        'decisionTaskCompletedEventId': 123
    },
    '''

    ACTIVITY_CREATION_RATE_EXCEEDED = 'ACTIVITY_CREATION_RATE_EXCEEDED'
    ACTIVITY_ID_ALREADY_IN_USE = 'ACTIVITY_ID_ALREADY_IN_USE'
    ACTIVITY_TYPE_DEPRECATED = 'ACTIVITY_TYPE_DEPRECATED'
    ACTIVITY_TYPE_DOES_NOT_EXIST = 'ACTIVITY_TYPE_DOES_NOT_EXIST'
    DEFAULT_HEARTBEAT_TIMEOUT_UNDEFINED = 'DEFAULT_HEARTBEAT_TIMEOUT_UNDEFINED'
    DEFAULT_SCHEDULE_TO_CLOSE_TIMEOUT_UNDEFINED = 'DEFAULT_SCHEDULE_TO_CLOSE_TIMEOUT_UNDEFINED'
    DEFAULT_SCHEDULE_TO_START_TIMEOUT_UNDEFINED = 'DEFAULT_SCHEDULE_TO_START_TIMEOUT_UNDEFINED'
    DEFAULT_START_TO_CLOSE_TIMEOUT_UNDEFINED = 'DEFAULT_START_TO_CLOSE_TIMEOUT_UNDEFINED'
    DEFAULT_TASK_LIST_UNDEFINED = 'DEFAULT_TASK_LIST_UNDEFINED'
    OPEN_ACTIVITIES_LIMIT_EXCEEDED = 'OPEN_ACTIVITIES_LIMIT_EXCEEDED'
    OPERATION_NOT_PERMITTED = 'OPERATION_NOT_PERMITTED'

    @property
    def activity_id(self):
        return self._get_data_attr('activityId')
    
    @property
    def cause(self):
        return self._get_data_attr('cause')
    
