# coding=utf-8
from .SWFEvent import SWFEvent

class ScheduleActivityTaskFailedEvent(SWFEvent):
    '''
    Failed to process ScheduleActivityTask decision. This happens when the decision isn't configured properly, for example the activity type specified isn't registered.

    'scheduleActivityTaskFailedEventAttributes': {
        'activityType': {
            'name': 'string',
            'version': 'string'
        },
        'activityId': 'string',
        'cause': 'ACTIVITY_TYPE_DEPRECATED'|'ACTIVITY_TYPE_DOES_NOT_EXIST'|'ACTIVITY_ID_ALREADY_IN_USE'|'OPEN_ACTIVITIES_LIMIT_EXCEEDED'|'ACTIVITY_CREATION_RATE_EXCEEDED'|'DEFAULT_SCHEDULE_TO_CLOSE_TIMEOUT_UNDEFINED'|'DEFAULT_TASK_LIST_UNDEFINED'|'DEFAULT_SCHEDULE_TO_START_TIMEOUT_UNDEFINED'|'DEFAULT_START_TO_CLOSE_TIMEOUT_UNDEFINED'|'DEFAULT_HEARTBEAT_TIMEOUT_UNDEFINED'|'OPERATION_NOT_PERMITTED',
        'decisionTaskCompletedEventId': 123
    },
    '''

    

    @property
    def activity_type(self):
        '''
        The activity type provided in the ScheduleActivityTask decision that failed.
    
        name (string) --
        The name of this activity.
    
        Note
        The combination of activity type name and version must be unique within a domain.
    
    
        version (string) --
        The version of this activity.
    
        Note
        The combination of activity type name and version must be unique with in a domain.
    
        :return dict:
        '''
        return self._get_data_attr('activityType')
    
    
    @property
    def activity_id(self):
        '''
        The activityId provided in the ScheduleActivityTask decision that failed.
    
        :return string:
        '''
        return self._get_data_attr('activityId')
    
    
    @property
    def cause(self):
        '''
        The cause of the failure. This information is generated by the system and can be useful for diagnostic purposes.
    
        Note
        If cause is set to OPERATION_NOT_PERMITTED , the decision failed because it lacked sufficient permissions. For details and example IAM policies, see Using IAM to Manage Access to Amazon SWF Workflows in the Amazon SWF Developer Guide .
    
        :return string:
        '''
        return self._get_data_attr('cause')
    
    
    @property
    def decision_task_completed_event_id(self):
        '''
        The ID of the DecisionTaskCompleted event corresponding to the decision that resulted in the scheduling of this activity task. This information can be useful for diagnosing problems by tracing back the chain of events leading up to this event.
    
        :return integer:
        '''
        return self._get_data_attr('decisionTaskCompletedEventId')
    
    
